"""Add level to UserData

Revision ID: 15e9e13b5ed1
Revises: 
Create Date: 2025-01-11 13:41:08.398445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15e9e13b5ed1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Sporty')
    op.drop_table('Calendar')
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credentials_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user_credentials', ['credentials_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('level')
        batch_op.drop_column('credentials_id')

    op.create_table('Calendar',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('date', sa.VARCHAR(length=50, collation='Polish_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=100, collation='Polish_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_credentials.id'], name='FK__Calendar__user_i__60A75C0F'),
    sa.PrimaryKeyConstraint('id', name='PK__Calendar__3213E83F02295ACF')
    )
    op.create_table('Sporty',
    sa.Column('Id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('Kategoria', sa.VARCHAR(length=50, collation='Polish_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('NazwaCwiczenia', sa.VARCHAR(length=255, collation='Polish_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('TypCwiczenia', sa.VARCHAR(length=50, collation='Polish_CI_AS'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Id', name='PK__Sporty__3214EC07AACB203D')
    )
    # ### end Alembic commands ###
